[package]
name = "filter_nulls_in_json"
version = "0.2.1"
description = ""
authors = ["Andrey Mnatsakanov <andrey@3ig.kiev.ua>"]
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
ordered-float = "3.0.0"
